export const capabilities = Object.freeze({
  browser: 'available',
  transactional_edits: 'available',
  project_queue: 'available',
  context_copy: 'available',
  observations: 'available',
  project_platform: 'available',
  project_source_editing: 'available',
  project_telemetry: 'available',
  embedding: 'unobserved',
  chat_handoff: 'unobserved',
  wake: 'unobserved',
  native_host_readiness: 'pending',
  dsh_host_control: 'unavailable',
});
